// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6tj1zWQKQGxsTdSy6md9ij_lArZ5y6A',
    appId: '1:678691806754:web:afc7a2ecf82b6bf47bb47b',
    messagingSenderId: '678691806754',
    projectId: 'wallet-2766a',
    authDomain: 'wallet-2766a.firebaseapp.com',
    storageBucket: 'wallet-2766a.firebasestorage.app',
    measurementId: 'G-VZD379KC0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDaR10WZ9c-m6gn0Aka9B_s6B8MnT-X-jo',
    appId: '1:678691806754:android:55eaa8f301c288717bb47b',
    messagingSenderId: '678691806754',
    projectId: 'wallet-2766a',
    storageBucket: 'wallet-2766a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHBZmG54KSlgtXI_HtoXnbE7_QF0yPIo',
    appId: '1:678691806754:ios:047aec56087ec1537bb47b',
    messagingSenderId: '678691806754',
    projectId: 'wallet-2766a',
    storageBucket: 'wallet-2766a.firebasestorage.app',
    iosBundleId: 'com.example.walletmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW6tj1zWQKQGxsTdSy6md9ij_lArZ5y6A',
    appId: '1:678691806754:web:77877b06832be94a7bb47b',
    messagingSenderId: '678691806754',
    projectId: 'wallet-2766a',
    authDomain: 'wallet-2766a.firebaseapp.com',
    storageBucket: 'wallet-2766a.firebasestorage.app',
    measurementId: 'G-8TE663CSG0',
  );
}
